name: Lint

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Lint with ruff
      uses: chartboost/ruff-action@v1
      with:
          src: "."
          version: 0.0.262